# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Solid State"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://standingwave.co/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "ceedon"
  homepage = "https://ceedon.io"

# If porting an existing theme
[original]
  name = "Solid State"
  homepage = "https://html5up.net"
